spring.application.name=transfer-engine


server.port=8080

spring.r2dbc.url=r2dbc:postgresql://localhost:5435/fluxpay_db
spring.r2dbc.username=fluxpay_user
spring.r2dbc.password=fluxpay_password

spring.sql.init.mode=always