spring.application.name=transfer-engine
server.port=8080

# Database Connection Configuration (Spring Data R2DBC)
spring.r2dbc.url=r2dbc:pool:postgresql://localhost:5435/fluxpay_db
spring.r2dbc.username=postgres
spring.r2dbc.password=postgres


#Reactive Connection Pool Tuning
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=30
spring.r2dbc.pool.max-idle-time=30m
spring.r2dbc.pool.max-life-time=60m
spring.r2dbc.pool.validation-query=SELECT 1


# Resilience4j Circuit Breaker Config
resilience4j.circuitbreaker.instances.externalBankService.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.externalBankService.sliding-window-size=10
resilience4j.circuitbreaker.instances.externalBankService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.externalBankService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.externalBankService.permitted-number-of-calls-in-half-open-state=3

# Reactive Schema Initialization
spring.sql.init.mode=always

